preset: laravel

risky: false

enabled:
  - alpha_ordered_imports
  - concat_with_spaces
  - no_empty_comment

disabled:
  - braces
  - phpdoc_no_package
  - concat_without_spaces
  - length_ordered_imports
  
finder:
  exclude:
    - "tests"
    - "app.php"
    - "ModelFactory.php"
    - "index.php"
    - "api.php"
    - "console.php"
    - "web.php"
    - "server.php"
  name:
    - "*.php"
